#!/bin/bash

chips=`plpinfo get --property=pulp_chip --silent`
platform=`plpinfo get --property=platform --silent | grep rtl`

if [ -n "$platform" ]; then
    for chip in $chips; do
      if [ $chip != "wolfe" ] && [ $chip != "vega" ] && [ $chip != "gap" ] && [ $chip != "gap8_revc" ] && [ $chip != "gap_rev1" ] && [ $chip != "arnold" ] && [ $chip != "vivosoc3" ]; then
        plpbuild --p $chip checkout build --stdout
      fi
    done
fi
