#ifndef __BSP__KRAKEN_H__
#define __BSP__KRAKEN_H__

#define CONFIG_HYPERFLASH
#define CONFIG_HYPERRAM

#define CONFIG_HYPERFLASH_HYPER_ITF 0
#define CONFIG_HYPERFLASH_HYPER_CS  1

#define CONFIG_HYPERRAM_HYPER_ITF 0
#define CONFIG_HYPERRAM_HYPER_CS  0
#define CONFIG_HYPERRAM_START     0
#define CONFIG_HYPERRAM_SIZE     (8<<20)

#endif
