 /* Header file generated by RedMulE Golden Model */
#ifndef __TENSOR_DIM__
#define __TENSOR_DIM__

#include "../archi_redmule.h"
#define M_SIZE  48 
#define N_SIZE  64 
#define K_SIZE  48
#define SRC_FMT FP16
#define DST_FMT FP16
#define FPFORMAT 16
uint8_t gemm_ops = GEMM; 

#endif
