// parasoft-begin-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits"
// parasoft-begin-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits"

/**********************************************************************
 * __LICENCE_BODY_COPYRIGHT__
 * __LICENCE_BODY_CADENCE__
 *
 * THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT
 *
 **********************************************************************/

#ifndef REG_MIPI_I3C_REGS_H_
#define REG_MIPI_I3C_REGS_H_

#include <cps_drv.h>

#include "mipi_i3c_regs_macros.h"

typedef struct __attribute__((packed)) MIPI_I3cRegs_s {
    volatile uint32_t DEV_ID;
    volatile uint32_t CONF_STATUS0;
    volatile uint32_t CONF_STATUS1;
    volatile char pad__0[0x4U];
    volatile uint32_t CTRL;
    volatile uint32_t PRESCL_CTRL0;
    volatile uint32_t PRESCL_CTRL1;
    volatile char pad__1[0x4U];
    volatile uint32_t MST_IER;
    volatile uint32_t MST_IDR;
    volatile uint32_t MST_IMR;
    volatile uint32_t MST_ICR;
    volatile uint32_t MST_ISR;
    volatile uint32_t MST_STATUS0;
    volatile uint32_t CMDR;
    volatile uint32_t IBIR;
    volatile uint32_t SLV_IER;
    volatile uint32_t SLV_IDR;
    volatile uint32_t SLV_IMR;
    volatile uint32_t SLV_ICR;
    volatile uint32_t SLV_ISR;
    volatile uint32_t SLV_STATUS0;
    volatile uint32_t SLV_STATUS1;
    volatile char pad__2[0x4U];
    volatile uint32_t CMD0_FIFO;
    volatile uint32_t CMD1_FIFO;
    volatile uint32_t TX_FIFO;
    volatile char pad__3[0x4U];
    volatile uint32_t IMD_CMD0;
    volatile uint32_t IMD_CMD1;
    volatile uint32_t IMD_DATA;
    volatile char pad__4[0x4U];
    volatile uint32_t RX_FIFO;
    volatile uint32_t IBI_DATA_FIFO;
    volatile uint32_t SLV_DDR_TX_FIFO;
    volatile uint32_t SLV_DDR_RX_FIFO;
    volatile uint32_t CMD_IBI_THR_CTRL;
    volatile uint32_t TX_RX_THR_CTRL;
    volatile uint32_t SLV_DDR_TX_RX_THR_CTRL;
    volatile uint32_t FLUSH_CTRL;
    volatile char pad__5[0x10U];
    volatile uint32_t TTO_PRESCL_CTRL0;
    volatile uint32_t TTO_PRESCL_CTRL1;
    volatile uint32_t DEVS_CTRL;
    volatile char pad__6[0x4U];
    volatile uint32_t DEV_ID0_RR0;
    volatile uint32_t DEV_ID0_RR1;
    volatile uint32_t DEV_ID0_RR2;
    volatile char pad__7[0x4U];
    volatile uint32_t DEV_ID1_RR0;
    volatile uint32_t DEV_ID1_RR1;
    volatile uint32_t DEV_ID1_RR2;
    volatile char pad__8[0x4U];
    volatile uint32_t DEV_ID2_RR0;
    volatile uint32_t DEV_ID2_RR1;
    volatile uint32_t DEV_ID2_RR2;
    volatile char pad__9[0x4U];
    volatile uint32_t DEV_ID3_RR0;
    volatile uint32_t DEV_ID3_RR1;
    volatile uint32_t DEV_ID3_RR2;
    volatile char pad__10[0x4U];
    volatile uint32_t DEV_ID4_RR0;
    volatile uint32_t DEV_ID4_RR1;
    volatile uint32_t DEV_ID4_RR2;
    volatile char pad__11[0x4U];
    volatile uint32_t DEV_ID5_RR0;
    volatile uint32_t DEV_ID5_RR1;
    volatile uint32_t DEV_ID5_RR2;
    volatile char pad__12[0x4U];
    volatile uint32_t DEV_ID6_RR0;
    volatile uint32_t DEV_ID6_RR1;
    volatile uint32_t DEV_ID6_RR2;
    volatile char pad__13[0x4U];
    volatile uint32_t DEV_ID7_RR0;
    volatile uint32_t DEV_ID7_RR1;
    volatile uint32_t DEV_ID7_RR2;
    volatile char pad__14[0x4U];
    volatile uint32_t DEV_ID8_RR0;
    volatile uint32_t DEV_ID8_RR1;
    volatile uint32_t DEV_ID8_RR2;
    volatile char pad__15[0x4U];
    volatile uint32_t DEV_ID9_RR0;
    volatile uint32_t DEV_ID9_RR1;
    volatile uint32_t DEV_ID9_RR2;
    volatile char pad__16[0x4U];
    volatile uint32_t DEV_ID10_RR0;
    volatile uint32_t DEV_ID10_RR1;
    volatile uint32_t DEV_ID10_RR2;
    volatile char pad__17[0x4U];
    volatile uint32_t DEV_ID11_RR0;
    volatile uint32_t DEV_ID11_RR1;
    volatile uint32_t DEV_ID11_RR2;
    volatile char pad__18[0x4U];
    volatile uint32_t SIR_MAP0;
    volatile uint32_t SIR_MAP1;
    volatile uint32_t SIR_MAP2;
    volatile uint32_t SIR_MAP3;
    volatile uint32_t SIR_MAP4;
    volatile uint32_t SIR_MAP5;
    volatile char pad__19[0x8U];
    volatile uint32_t GPIR_WORD0;
    volatile uint32_t GPIR_WORD1;
    volatile uint32_t GPIR_WORD2;
    volatile uint32_t GPIR_WORD3;
    volatile uint32_t GPIR_WORD4;
    volatile uint32_t GPIR_WORD5;
    volatile uint32_t GPIR_WORD6;
    volatile uint32_t GPIR_WORD7;
    volatile uint32_t GPIR_WORD8;
    volatile uint32_t GPIR_WORD9;
    volatile uint32_t GPIR_WORD10;
    volatile uint32_t GPIR_WORD11;
    volatile uint32_t GPIR_WORD12;
    volatile uint32_t GPIR_WORD13;
    volatile uint32_t GPIR_WORD14;
    volatile uint32_t GPIR_WORD15;
    volatile uint32_t GPIR_WORD16;
    volatile uint32_t GPIR_WORD17;
    volatile uint32_t GPIR_WORD18;
    volatile uint32_t GPIR_WORD19;
    volatile uint32_t GPIR_WORD20;
    volatile uint32_t GPIR_WORD21;
    volatile uint32_t GPIR_WORD22;
    volatile uint32_t GPIR_WORD23;
    volatile uint32_t GPIR_WORD24;
    volatile uint32_t GPIR_WORD25;
    volatile uint32_t GPIR_WORD26;
    volatile uint32_t GPIR_WORD27;
    volatile uint32_t GPIR_WORD28;
    volatile uint32_t GPIR_WORD29;
    volatile uint32_t GPIR_WORD30;
    volatile uint32_t GPIR_WORD31;
    volatile uint32_t GPOR_WORD0;
    volatile uint32_t GPOR_WORD1;
    volatile uint32_t GPOR_WORD2;
    volatile uint32_t GPOR_WORD3;
    volatile uint32_t GPOR_WORD4;
    volatile uint32_t GPOR_WORD5;
    volatile uint32_t GPOR_WORD6;
    volatile uint32_t GPOR_WORD7;
    volatile uint32_t GPOR_WORD8;
    volatile uint32_t GPOR_WORD9;
    volatile uint32_t GPOR_WORD10;
    volatile uint32_t GPOR_WORD11;
    volatile uint32_t GPOR_WORD12;
    volatile uint32_t GPOR_WORD13;
    volatile uint32_t GPOR_WORD14;
    volatile uint32_t GPOR_WORD15;
    volatile uint32_t GPOR_WORD16;
    volatile uint32_t GPOR_WORD17;
    volatile uint32_t GPOR_WORD18;
    volatile uint32_t GPOR_WORD19;
    volatile uint32_t GPOR_WORD20;
    volatile uint32_t GPOR_WORD21;
    volatile uint32_t GPOR_WORD22;
    volatile uint32_t GPOR_WORD23;
    volatile uint32_t GPOR_WORD24;
    volatile uint32_t GPOR_WORD25;
    volatile uint32_t GPOR_WORD26;
    volatile uint32_t GPOR_WORD27;
    volatile uint32_t GPOR_WORD28;
    volatile uint32_t GPOR_WORD29;
    volatile uint32_t GPOR_WORD30;
    volatile uint32_t GPOR_WORD31;
    volatile char pad__20[0x60U];
    volatile uint32_t asf_int_status;
    volatile uint32_t asf_int_raw_status;
    volatile uint32_t asf_int_mask;
    volatile uint32_t asf_int_test;
    volatile uint32_t asf_fatal_nonfatal_select;
    volatile char pad__21[0xCU];
    volatile uint32_t asf_sram_corr_fault_status;
    volatile uint32_t asf_sram_uncorr_fault_status;
    volatile uint32_t asf_sram_fault_stats;
    volatile char pad__22[0x4U];
    volatile uint32_t asf_trans_to_ctrl;
    volatile uint32_t asf_trans_to_fault_mask;
    volatile uint32_t asf_trans_to_fault_status;
    volatile char pad__23[0x4U];
    volatile uint32_t asf_protocol_fault_mask;
    volatile uint32_t asf_protocol_fault_status;
} MIPI_I3cRegs;

#endif /* REG_MIPI_I3C_REGS_H_ */

// parasoft-end-suppress MISRA2012-RULE-1_1_a_c99-2 "C99 - limits"
// parasoft-end-suppress MISRA2012-RULE-1_1_a_c90-2 "C90 - limits"

