APP = neureka_test
APP_SRCS += neureka_test.c
APP_CFLAGS += -O3 -g -Iinc -Istreamin_fs1_output_64x16x16_input_32x16x16/inc -Ipadding_1111_fs3_output_32x16x16_input_32x16x16/inc -Ino_normquant_stride2_output_64x16x16_input_64x32x32/inc -Iavgpool_fs3_dw_output_64x32x32_input_64x32x32/inc -Istride2_fs1_output_32x16x16_input_64x32x32/inc
# APP_CFLAGS += -O3 -g -Iinc -Iavgpool_fs3_dw_output_64x32x32_input_64x32x32/inc -Ino_normquant_stride2_output_64x16x16_input_64x32x32/inc -Istreamin_fs1_output_64x16x16_input_32x16x16/inc -Istride2_fs1_output_32x16x16_input_64x32x32/inc
PMSIS_OS=pulpos

include $(RULES_DIR)/pmsis_rules.mk
